### PR TITLE
August Maintenance Tasks

### LINKED ISSUE #449: remove "spotlight" section from status summary emails
don't have more details. let me know if this makes sense.

### LINKED ISSUE #483: showing past events on project pages
(This is the low-priority maintenance item for August.)

As you can see in the sidebar on this page, Events that reference a Project do appear on the Project page:
http://pulitzercenter.org/project/asia-china-beijing-rat-tribe-migrant-workers-poverty-service-poor-housing

However, the sidebar block only currently shows upcoming Events. Pulitzer Center would like to find a way to show Recent (past) Events because: 1) this provides examples for users of the types of Events that Pulitzer can host, 2) this provides action/impact info for funders, and 3) this provides a quick reference for Pulitzer staff who are do project-based funder reports.

Ideas:
1. They would be open to keeping the Recent Events in the sidebar (maybe with some sort of distinguisher) - it is important to note that some projects (like http://pulitzercenter.org/project/fractured-lands) have a bunch of Related Events. Make sure to use that as a use case during testing.

2. Add another tab to where Stories/Education Resources/Pulitzer Center Updates already live...not sure if there is space for this and/or if it would make the tabs seem less tab-y?

3. Open to your thoughts if you have other ideas?

Whatever we do, we'll need to get Jeff & Nathalie an hours estimate first.

### LINKED ISSUE #486: add last updated date to bio pages
They'd like to add "Last Updated on DATE" to bio pages, just below the bio text.

Given that bios go out of date so quickly, they think it would be nice for visitors to be able to see how old they are. Here's an example of the page type: http://pulitzercenter.org/people/jon-sawyer

### PR DESCRIPTION
**Pull request by xaqrox**
Available on http://pccr.radcampaign.com.
- Close #486 &mdash; Add "Last Updated" field to users.
- Close #449 &mdash; Remove "Spotlight" section from status summary email.
- Close #483 &mdash; Add Recent Events block to Projects sidebar.

### CODE REVIEW

**Comment by daniellerad** [comment]
Reviewed, and then sent to Jeff for review.

**Comment by daniellerad** [comment]
Jeff gave the green light. Once @jselt reviews, we are good to deploy live.

**Comment by jselt** [comment]
👍  - not sure I really need to review when two others have - but I took a quick look at the code - looks fine.

**Comment by daniellerad** [comment]
Green light from Jeff! Good to deploy.

**Pull request merged**
