### PR TITLE
Taxonomy renaming.

### LINKED ISSUE #263: taxonomy naming changes
- [x] Topics -> Tags

- [x] Blogs -> Pulitzer Center Updates

- [x] Tags -> Content Groupings

- [x] Education -> Education Resources

### PR DESCRIPTION
**Pull request by xaqrox**
Should fix #263, see that issue for the pairs. Also all mentions of `section` vocab and `field_sections` should be gone.

### CODE REVIEW

**Comment by jselt** [comment]
I don't see a field that references the Content Grouping taxonomy anywhere - it's vid is 16 and I see nothing for it in the field list. Is that right?

**Comment by daniellerad** [comment]
yerp. that's right.

**Comment by jselt** [comment]
but we're keeping the taxonomy - even though it's not used

**Comment by daniellerad** [comment]
yerp. that's right.

**Comment by jselt** [comment]
okey dokey :)

**Pull request merged**
