### PR TITLE
Lesson builder resource search fix

### LINKED ISSUE #296: lesson builder searching resources doesn't match live site results
Go to any lesson, and click "use lesson" then"modify". Edit Resources, and attempt a search. For example: keyword "AIDS" and media "photo" - the results don't match the live site.

### PR DESCRIPTION
**Pull request by xaqrox**
Pull, revert, lesson builder resource search (when editing a lesson) should bring up Story content. Closes #296.

### CODE REVIEW

**Comment by jselt** [comment]
Doesn't seem to work as I expect. I search using the title of a story both with and without quotes. The story did not come up. But an unrelated project does

draft lessons

Just searching one of the words brings up the project the story is attached to, along with some other results including one story.

draft lessons-2

Since I'm not as familiar with the lesson builder search is this basically what I should expect? I do see some stories being returned.

**Comment by jselt** [comment]
@xaqrox  - realized I didn't tag you in my previous comment

**Comment by xaqrox** [comment]
Works for me... how fresh is your db clone?

**Comment by jselt** [comment]
Should it matter? I'm searching for a story that exists locally

**Pull request merged**
