### PR TITLE
Ensuring uniform styling for mobile nav

### LINKED ISSUE #333: mobile hamburger menu styles
In the hamburger menu, please change the top tier of homepage links to be the same size and font style as the bottom tier of links. Everything should be the style used for the main navigation links of Reporting, Resources for Teachers, Journalism Grants.

### PR DESCRIPTION
**Pull request by AlexandraCasser**
1.  Pull, clear cache.
2.  Shrink the viewport to see the mobile nav.  It should look like this:
pulitzer dev- iphone 6 plus

Closes #333

### CODE REVIEW

**Comment by jselt** [comment]
This should be done in _header.scss

Font settings up to 992px start at 142 of that file.

You would then need to update the secondary nav style in the medium breakpoint line 331

**Comment by AlexandraCasser** [comment]
@jselt Thanks, fixed.

**Comment by jselt** [comment]
Cool - can you set the secondary nav to the sans-serif font for the medium breakpoint and above - just add it to `li` definition that starts on line 334 of _header.scss

**Comment by AlexandraCasser** [comment]
Sure.  It seems to work without it, so it that just a case of best practices?

**Comment by jselt** [comment]
it does? When you expand your browser the nav next to the social icons in the header have the sans-serif font?

**Comment by jselt** [comment]
sans-serif - not the serif - when the menus expand to desktop the secondary is supposed to be sans-serif at that point

**Pull request merged**
